### ISSUE TITLE
milvus_minio1.1和milvus_minio-proxy.1一直报错处于ready状态报错"task: non-zero exit (1)"

### ISSUE THREAD

**Issue by fuhuaweiyang** [yangxianpku/milvus#2]
请问在docker stack ps  milvus --no-trunc命令查看中milvus_minio1.1和milvus_minio-proxy.1一直报错处于ready状态报错"task: non-zero exit (1)"是为什么，milvus_minio-proxy.2能正常running

**Comment by yangxianpku** [comment]
进去瞧瞧日志

**Comment by fuhuaweiyang** [comment]
已解决
